### ISSUE TITLE
Orthographic + graticule is giving a range error

### ISSUE THREAD

**Issue by jimmyff** [luizbarboza/d4_geo#2]
Hey just wanted to flag I think there is an issue with orthographic projection and rendering graticule, it throws a range error. Other projections seem to work fine though

```
RangeError (index): Invalid value: Not in inclusive range 0..1: 2

When the exception was thrown, this was the stack:
#0      List._setIndexed (dart:core-patch/growable_array.dart:274:49)
growable_array.dart:274
#1      List.[]= (dart:core-patch/growable_array.dart:269:5)
growable_array.dart:269
#2      geoClipCircle.clipLine.<anonymous closure> (package:d4_geo/src/clip/circle.dart:147:49)
circle.dart:147
#3      clip.<anonymous closure>.pointLine (package:d4_geo/src/clip/clip.dart:29:19)
clip.dart:29
#4      _transformRotate.<anonymous closure> (package:d4_geo/src/projection/projection.dart:20:52)
projection.dart:20
#5      GeoTransform.call.<anonymous closure> (package:d4_geo/src/transform.dart:56:49)
transform.dart:56
#6      _transformRadians.<anonymous closure> (package:d4_geo/src/projection/projection.dart:16:15)
projection.dart:16
#7      GeoTransform.call.<anonymous closure> (package:d4_geo/src/transform.dart:56:49)
transform.dart:56
#8      GeoStream._streamLine (package:d4_geo/src/stream.dart:159:12)
stream.dart:159
#9      GeoStream._streamGeometryType.<anonymous closure> (package:d4_geo/src/stream.dart:135:9)
stream.dart:135
#10     GeoStream._streamGeometry (package:d4_geo/src/stream.dart:100:45)
stream.dart:100
#11     GeoStream.call (package:d4_geo/src/stream.dart:94:7)
stream.dart:94
#12     GeoPath.call (package:d4_geo/src/path/path.dart:84:28)
path.dart:84
```

**Comment by luizbarboza** [comment]
The bug has been fixed. Thanks for pointing it out.
